### ISSUE TITLE
Предупреждения

### ISSUE THREAD

**Issue by Sbotkin** [FighterX/SOVIET-STATION#15]
Впили предупреждения переносимые из раунда в раунд.

**Comment by KRLL** [comment]
А нафиг это надо? Предупреждения на то и предупреждения, чтобы они были на раунд.

**Comment by Sbotkin** [comment]
Они не особо нужны в таком случае. А так их можно будет выдавать действительно за мелкие ошибки. Ну совсем мелкие.
