### ISSUE TITLE
Очки ночного видения

### ISSUE THREAD

**Issue by Sbotkin** [FighterX/SOVIET-STATION#17]
Может уже сделать так, чтобы с их помощью было хоть что-то видно?
Впилить им функционал toggle-darkness. И по возможности зеленый фильтр.
![photo](https://f.cloud.github.com/assets/5092934/2508350/a4bb1ae4-b3d5-11e3-94dd-89022195fffa.jpg)

**Comment by KRLL** [comment]
Это не должно быть сложно, так как для фильтра можно взять код тумана в глазах, а для функционала взять код самой кнопки. Пусть Алексикс делает, я за.

**Comment by aleksix** [comment]
Странно. У меня всё в норме. Посмотрю, как смогу
