### ISSUE TITLE
Полный админ-инвиз

### ISSUE THREAD

**Issue by Sbotkin** [FighterX/SOVIET-STATION#19]
Запилить нормальный инвиз админов (+STEALTH), который не будет палиться строчкой в adminwho.

**Comment by Opex1989** [comment]
Зойчем?

**Comment by aleksix** [comment]
Так я ж уже фиксил modwho, не? Если админ в инвизе, то он его не палит. В пулах ещё лежит.

**Comment by KRLL** [comment]
Лол, Сботкин, эту хрень уже давно пофиксили. Там всего одну строчку добавить и всё. Так что закрывай.

**Comment by Sbotkin** [comment]
Ничего не знаю, фиксите.
![shot](https://f.cloud.github.com/assets/5092934/2512741/661978f4-b429-11e3-8bb5-211ad8cd6d9a.jpg)

**Comment by aleksix** [comment]
Всё так и должно быть. Админы админов должны видеть

**Comment by KRLL** [comment]
Да, так что закрывай.
