### ISSUE TITLE
Шредер

### ISSUE THREAD

**Issue by Sbotkin** [FighterX/SOVIET-STATION#20]
Очень нужен таковой в офис ХоПа, конференц-зал, офис вардена, приемную медбея, [вставьте название кабинета сюда]. Сжигать листы или удалять их админкой это какой-то долбоебизм.

**Comment by KRLL** [comment]
Кстати да, а он прав. Всё время мешало то, что приходится в мусорку кидать секретные документы, где их потом продаёт КМ.

**Comment by aleksix** [comment]
А кидать доки в папки, которые никогда никто не проверяет? Да и зачем выкидывать документы, есть же папки и ящики.
А так, да, идея. КРЛЛ, возьмёшься или мне?

**Comment by KRLL** [comment]
Ладно, сейчас. Только спрайт сами делайте, у меня нет. Пойдёт что то типа настольного зарядника для пушек, только немного другое.

**Comment by Sbotkin** [comment]
Алексикс, шредеры придумали для утилизации секретных документов, ага.

**Comment by llegoman007** [comment]
Ща я вам наспрайчу шредера из черепашек нинзя
P.S. Барсик,  я выполнил твое задание
