### ISSUE TITLE
Локальный саунд

### ISSUE THREAD

**Issue by Sbotkin** [FighterX/SOVIET-STATION#30]
Почему бы не добавить возможность делать локальный саунд, вроде того же джукбокса, только в любом месте и с заданным размером? Это позволило бы, например, пилить концерты, интересные сценки и пр. не трахая музыкой всех игроков одновременно.

**Comment by aleksix** [comment]
Кхм. Поделюсь историей BYOND. Изначально, это был движок для текстовых мультиплеерных РПГ(MUD), и звался он DUNG(лучше не переводить). Как можно догадаться, в тексте музыки мало.
Затем он эволюционировал в движок для тайловых jRPG, где хватало музыки на заднем плане, а также звуков атаки, спелов и т.п.
СС - динамичная игра, в которой персонажи могут и не слышать звуков из-за РП.
Так вот. У нас есть куча каналов, автораспределение звуков по ним и пауза. Локальные звуки а-ля мой хреновый джукбокс будут сильно нагружать и серв, и клиентов из-за странной системы остановки звука.

А ещё я глухой в СС и звуков не загружаю
